import './globals.css'
import "tw-elements/dist/css/tw-elements.min.css";
import { ABeeZee } from "next/font/google"

const abeezee = ABeeZee({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={abeezee.className}>
        <div className='bg-gradient-to-r from-gray-100 to-gray-50'>
        {children}
        </div>
        </body>
    </html>
  )
}
